# Welcome to Jekyll!

# Website settings
title: "Greg Dolder"
description: "Greg Dolder's living CV|Resume."
keywords: "gregdolder, greg dolder,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "https://gregdolder.github.io"
# url: "http://127.0.0.1:4000"

# blog img path
img_path: 'http://gregdolder.github.io/static/img/blog'

# author
author:
  name: 'Greg'
  first_name: 'Greg'
  last_name: 'Dolder'
  email: 'dolder14@gmail.com'
  facebook_username: 'gdolder'
  github_username: 'gregdolder'
  head_img: 'static/img/landing/greg-profile.jpg'

# social link
jingyu:
  first_name: 'Dolder'
  last_name: 'Greg'
  description: 'Technology Professional'
  link: 'http://linkedin.com/in/gregdolder'
  email: 'dolder14@gmail.com'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Projects'
  blog: 'Blog'
  link: 'Contact'

# my projects
project:
  specialized:
    name: 'Specialized.com'
    url: 'https://www.specialized.com'
    img: 'static/img/landing/specialized-logo.png'
  jalpc:
    name: 'Jalpc'
    url: '/Jack614/jalpc_jekyll_theme'
    img: 'static/img/landing/jekyll.png'
  angularjs:
    name: 'Jalpc-A'
    url: '/gdolder/Jalpc-A'
    img: 'static/img/landing/angularjs.png'
  Rsser:
    name: 'Rsser'
    url: '/gdolder/Rsser'
    img: 'static/img/landing/rsser.png'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
#bshare:
#  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
#ba:
#  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
